import type { Metadata } from "next";
import { BrainCircuit, FileText } from "lucide-react";

export const metadata: Metadata = {
  title: "Intelligence Brief — LOGISTIQS Intelligence",
  description: "Daily AI-generated operational intelligence and executive decision support.",
};

export default function IntelligenceBriefPage() {
  return (
    <div className="max-w-6xl mx-auto space-y-6">
      <div>
        <h1 className="text-xl sm:text-2xl font-bold text-slate-900 dark:text-white">
          Intelligence Brief
        </h1>
        <p className="text-sm text-slate-500 dark:text-slate-400 mt-0.5">
          Daily operational intelligence brief generated by the Executive Decision Intelligence engine
        </p>
      </div>

      <div className="bg-white dark:bg-slate-900 rounded-xl border border-slate-200 dark:border-slate-800 p-6">
        <div className="flex items-center gap-3 mb-6 pb-4 border-b border-slate-100 dark:border-slate-800">
          <BrainCircuit className="h-5 w-5 text-blue-500" />
          <div>
            <h2 className="text-sm font-semibold text-slate-900 dark:text-white">
              Today&apos;s Brief — {new Date().toLocaleDateString("en-US", { dateStyle: "long" })}
            </h2>
            <p className="text-xs text-slate-500 dark:text-slate-400">
              AI-generated at 06:00 this morning
            </p>
          </div>
        </div>

        <div className="flex flex-col items-center justify-center py-12 text-center">
          <FileText className="h-12 w-12 text-slate-300 dark:text-slate-600 mb-4" />
          <h3 className="text-lg font-semibold text-slate-900 dark:text-white mb-1">
            Daily Brief Content
          </h3>
          <p className="text-sm text-slate-500 dark:text-slate-400 max-w-md">
            The full daily intelligence brief — including prioritised decisions, risk forecasts,
            and operational recommendations from all four AI engines — will be displayed here
            each morning.
          </p>
        </div>
      </div>
    </div>
  );
}
